server:
    port: ${VH_SERVER_PORT:8080}

spring:
    application:
        name: VaulthiveServer

    datasource:
        url: ${VH_DATABASE_URL}?createDatabaseIfNotExist=true
        username: ${VH_DATABASE_USERNAME}
        password: ${VH_DATABASE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        database: mysql